import { Provider } from '@/app/provider';
import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const Layout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => <Provider>{children}</Provider>;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" className="h-full bg-white">
      <body className="h-full">
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
